server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

management:
  health:
    ldap:
      enabled: false

spring:
  ldap:
    # openldap accessed through docker's internal network
    urls: ldap://openldap:1389
    base: dc=arima,dc=eu
